coderamp-labs/gitingest

.gitignore
requirements.txt
src/cli.py
src/ingest.py

It would be nice to have the ability to run the ingestion against a local repository as a command-line script so offering this to the main repo.

added click support for local repo ingestion

---

Dockerfile
requirements.txt
src/ingest.py

Hello, this PR fixes some bugs that might lead to security-related issues:
1. Run the docker installation using an unprivileged user
2. Add some recursion and size limits to prevent DOS
3. Fix some bugs related to symbolic links
4. Add a missing dependency to requirements.txt

Fix file management and permissions issues

---

README.md
src/main.py

- Added support for configuring allowed hosts dynamically using the ALLOWED_HOSTS environment variable.
- Fallback to a default list of allowed hosts: ["gitingest.com", "*.gitingest.com", "gitdigest.dev", "localhost"]
- Ensures compatibility with custom deployments while maintaining existing defaults.
- Updated src/main.py to implement the changes.
- Updates README.md on usage

feat: Make TrustedHostMiddleware configurable via ALLOWED_HOSTS env var

---

README.md
src/templates/components/github_form.jinja
src/templates/index.jinja
src/tests/test_parse_query.py
src/utils/parse_query.py

You can now paste links from other platforms if they follow the same pattern as github: https://xxxxxxx/username/repo.git

Add support for github alternatives

---

.gitignore
README.md
requirements.txt
setup.py
src/cli.py
src/ingest.py

This PR adds a command-line interface to gitingest, allowing users to analyze local directories without needing to run the web server. The CLI tool can be installed globally and provides similar functionality to the web interface.
- Global command-line tool installation via `pip install -e .`
- Analyze any local directory with `gitingest /path/to/directory`
- Configurable output location with `-o` flag
- Support for custom file size limits with `--max-size`
- Additional ignore patterns via `-i` flag
- Maintains compatibility with web app's ingest functionality
- Automatic file type detection and text content extraction
- Directory tree visualization
- File content summary with statistics
```bash
gitingest ~/projects/myproject
gitingest ~/projects/myproject -o ~/Desktop/analysis.txt …
```

feat(cli): Add Global CLI Tool for Local Directory Analysis

---

src/gitingest/ingest_from_query.py

Modified `create_file_content_string()` to show root level README.md first in the repository content output file using a two pass approach. This is motivated by the [structure](https://github.com/AnswerDotAI/llms-txt) proposed by AnswerDotAI for llms.txt files.
Ran the test suite and all 11 tests pass.

Place repository root level readme first in file content output

---

.pre-commit-config.yaml
README.md
src/config.py
src/gitingest/cli.py
src/gitingest/clone.py
src/gitingest/ingest_from_query.py
src/gitingest/parse_query.py
src/gitingest/tests/test_clone.py
src/gitingest/tests/test_ingest.py
src/gitingest/tests/test_parse_query.py
src/gitingest/utils.py
src/main.py
src/process_query.py
src/server_utils.py

This PR includes a combination of refactoring, documentation, and code cleanup tasks to improve the codebase's structure, readability, and maintainability. The changes include:
- Simplified logic in the `_should_exclude` function in `ingest_from_query.py`.
- Reorganized `clone.py` by moving the `clone_repo` function to the top of the file, above helper functions.
- Prefixed helper functions with an underscore for clarity and convention.
- Added docstrings to functions in `process_query.py` and the `logSliderToSize` function in `server_utils.py`.
- Enhanced `main.py` with docstrings and additional comments for clarity.
- Moved the comment for the `async_timeout` function into its body for better placement.
- Added `markdownlint` to pre-commit hooks for enforcing markdown standards and …

Refactor, Documentation, and Code Cleanup

---

src/gitingest/parse_query.py

include/exclude patterns was not splitted correctly
Issue https://github.com/cyclotruc/gitingest/issues/75

FIX include patterns

---

src/gitingest/cli.py
src/gitingest/clone.py
src/gitingest/exceptions.py
src/gitingest/ingest.py
src/gitingest/ingest_from_query.py
src/gitingest/parse_query.py
src/gitingest/utils.py
src/process_query.py
src/routers/download.py
src/routers/dynamic.py
src/routers/index.py

This PR introduces two main changes:
1. Adds docstrings to various functions to improve code documentation and readability.
2. Moves the main function `process_query` to the top of the `process_query.py` file for better organization.
3. Prefixes helper functions with an underscore to follow Python naming conventions for internal functions.
4. Moves the `AsyncTimeoutError` exception to the `gitingest.exceptions` module for better exception handling organization.
These changes enhance code clarity, maintainability, and adhere to best practices in Python code organization and exception management.

Add docstrings, refactor process_query, and move AsyncTimeoutError to gitingest.exceptions

---

src/gitingest/tests/test_clone.py

Part of #55 
Added Some tests for clone.py
1. Invalid URL Check
2. Invalid Local Path Check
3. Clone with Custom branch 
4. Git command failure check
5. Default Shallow Clone check
cc @cyclotruc

test: added unit tests for clone.py

---

src/gitingest/tests/test_parse_query.py

Part of #55
Added Some more unit tests for `parse_query.py`
cc @cyclotruc

test: added unit test for parse_query

---

.github/workflows/ci.yml
src/gitingest/parse_query.py
src/gitingest/tests/test_parse_query.py

Closes #92 
Fairly simple fix. Should deal with the problem. 
Tested it locally and it works.
cc @cyclotruc

fix: http error

---

.dockerignore
.pre-commit-config.yaml
README.md
pyproject.toml
pytest.ini
src/config.py
src/gitingest/__init__.py
src/gitingest/cli.py
src/gitingest/clone.py
src/gitingest/exceptions.py
src/gitingest/ignore_patterns.py
src/gitingest/ingest.py
src/gitingest/ingest_from_query.py
src/gitingest/parse_query.py
src/gitingest/tests/conftest.py
src/gitingest/utils.py
src/main.py
src/process_query.py
src/routers/__init__.py
src/routers/download.py
src/routers/dynamic.py
src/routers/index.py
src/server_utils.py
tests/.pylintrc
tests/conftest.py
tests/test_clone.py
tests/test_ingest.py
tests/test_parse_query.py

This PR refactors the project structure and enhances code quality by:
- Refactoring the `_scan_directory` function in `src/gitingest/ingest_from_query.py` by extracting loop logic into the new `_process_item` function, and further separating functionality into `_process_symlink` and `_process_file`
- Replacing multiple return statements with error raising and catching, introducing custom exceptions (`MaxFilesReachedError`, `MaxFileSizeReachedError`, `AlreadyVisitedError`) in the `_process_item` and `_scan_directory` functions
- Enhancing the logic in the `process_query` function in `src/process_query.py` for better flow and maintainability
- Improving the logic in `_generate_token_string` in `src/gitingest/ingest_from_query.py`
- Refining the `download_ingest` function in …

Refactor project structure, enhance logic, update configurations, and improve code quality

---

README.md
src/config.py
src/gitingest/cli.py
src/gitingest/exceptions.py
src/gitingest/ignore_patterns.py
src/gitingest/utils.py
src/templates/api.jinja
src/templates/base.jinja

This PR updates all occurrences of the project name to consistently read “**Gitingest**”, aligning with the discussion in issue #99. 
- Standardizes “**Git ingest**” / “**GitIngest**” references to “**Gitingest**”
- Resolves https://github.com/cyclotruc/gitingest/issues/99

chore: standardize references to "Gitingest" (resolves Issue #99)

---

src/config.py
src/gitingest/ingest.py
src/gitingest/ingest_from_query.py
src/gitingest/parse_query.py
src/main.py
src/process_query.py
src/routers/download.py
tests/conftest.py
tests/test_ingest.py
tests/test_parse_query.py

This PR replaces all occurrences of os.path with the `pathlib` library to enhance code clarity, maintainability, and cross-platform consistency. Key changes include:
- Converting string-based path manipulations to `Path` objects.
- Using `path.relative_to(...)` to obtain relative paths instead of naive string replacements.
- Replacing `os.path.join()`, `os.path.exists()`, `os.path.abspath(...)`, `os.path.basename(...)`, `os.path.dirname(...)`, `os.path.getctime(...)`, `os.listdir(...)`, and similar functions with the equivalent `Path` methods.
By leveraging pathlib’s object-oriented approach, we ensure fewer edge cases in path handling, especially on different operating systems. The tests have been updated to reflect these changes and should pass as expected.

refactor: refactor codebase to use pathlib instead of os.path

---

tests/conftest.py
tests/test_clone.py
tests/test_parse_query.py

Added documentation to the test files promoting 100% docstring coverage.
@cyclotruc

docs: added docs for test files

---

README.md
src/gitingest/__init__.py

This PR fixes linting issues in `README.md` and corrects a spelling error in `__init__.py.`

fix: fix README linting issues and correct spelling error

---

src/gitingest/parse_query.py
tests/test_parse_query.py

This pull request addresses the issue where the `injest` URL field was not case insensitive, as described in https://github.com/cyclotruc/gitingest/issues/110.
- Added `source = source.lower()` in the `parse_query` function to handle mixed-case URLs.
- Implemented a new test `test_parse_query_mixed_case` to ensure that URLs with uppercase letters are processed correctly.
These changes ensure that URLs with different casing are correctly recognized, resolving the reported issue.
Resolves https://github.com/cyclotruc/gitingest/issues/110

fix: make ingest URL field case insensitive in parse_query

---

src/gitingest/__init__.py
src/gitingest/ingest.py
src/gitingest/ingest_from_query.py
src/gitingest/notebook_utils.py
src/process_query.py
tests/conftest.py
tests/test_ingest.py
tests/test_notebook_utils.py

This PR introduces the `process_notebook` function to process `.ipynb` files and return them as Python scripts, converting markdown and raw cells into multi-line string literals. It also refactors the function name `ingest_from_query` to `run_ingest_query` in `ingest_from_query.py` to avoid naming conflicts with the module, ensuring clearer code organization.
**Changes include:**
- Adding the `process_notebook` function to handle Jupyter notebooks.
- Renaming the `ingest_from_query` function to `run_ingest_query` to avoid naming conflicts with the module.
- Updating `_read_file_content` to invoke `process_notebook` for `.ipynb` files.
- Adding unit tests in `test_notebook_utils.py` for the notebook processing logic.
- Adding integration tests in `test_ingest.py` to verify that `.ipynb` …

feat: add support for improved handling of jupyter notebooks

---

tests/test_query_ingestion.py

Added test case for verifying file pattern matching with `*.txt` include pattern.
- Added `test_include_txt_pattern` to verify that:
- Only .txt files are included when using `*.txt` pattern
- Python (.py) files are correctly excluded
- All expected .txt files are found in the correct locations
Addresses TODO comment in test_query_ingestion.py for testing include patterns.
- Test has been run locally and passes
- No modifications to existing code, only adds new test coverage

Add test for *.txt include pattern filtering

---

tests/test_query_ingestion.py

Test that when using a pattern for a non-existent file extension `*.qwerty`,
no files are processed despite other valid files being present in the directory.
Test that when using a pattern for a non-existent file extension `*.qwerty`,
no files are matched or included in the result, but the directory structure
information is still captured.
This test verifies:
1. The scan completes without errors
2. No files are matched with the non-existent extension
3. Directory structure is still captured but empty since no files match
4. File information is present but content is ignored due to no matches

Add test for non-existent file extension pattern (*.qwerty)

---

tests/test_query_ingestion.py

This PR adds comprehensive test coverage for directory pattern matching in GitIngest, focusing on how different patterns interact with directory structures and file inclusion. Through the development process,  discovered several important behaviors of the pattern matching system.
Initially, started with previous assumption that patterns would work similar to common glob patterns:
- `src/*` would only match direct children
- `src/` would match recursively
- Leading slashes would be normalized
However, through testing, discovered the actual behavior:
- `src/*` matches all files recursively under src/
- Leading slash patterns (`/src/*`) don't match any files
- The proper pattern for explicit recursive matching is `src/**`
Encountered cross-platform compatibility issues with path separators: …

Enhanced Directory Pattern Matching Test Coverage

---

src/gitingest/exceptions.py
src/gitingest/notebook_utils.py
src/gitingest/query_ingestion.py
tests/test_notebook_utils.py

This PR introduces an optional parameter (`include_output`) to the `process_notebook` function, enabling control over whether code cell outputs are included in the generated Python script. 
1. **`InvalidNotebookError`**: Added a new custom exception to better handle invalid or non-decodable notebook files.
2. **`process_notebook` enhancements**:
- Accepts a new boolean parameter (`include_output`) defaulting to `True`.
- Extracts cell outputs and appends them as commented blocks (`# Output: ...`) in the generated script if `include_output=True`.
- Refactored internal logic into helper functions (`_process_cell`, `_extract_output`) for better readability.
3. **Exception handling**:
- `InvalidNotebookError` is now caught alongside `OSError` when reading notebook files in …

feat: add optional notebook cell output inclusion to `process_notebook` utility

---

src/config.py
src/gitingest/cli.py
src/gitingest/ignore_patterns.py
src/gitingest/query_ingestion.py
src/gitingest/query_parser.py
src/gitingest/repository_ingest.py
src/main.py
src/query_processor.py
tests/conftest.py
tests/query_parser/test_git_host_agnostic.py
tests/query_parser/test_query_parser.py
tests/test_query_ingestion.py

This PR replaces the old dictionary-based query object with a new `ParsedQuery` dataclass, improving type safety and readability across the codebase. 
- Introduces a `ParsedQuery` `dataclass` that consolidates all query-related fields (repo, branch, commit, patterns, etc.)
- Updates the following functions in the `query_parser` module to return a query of type `ParsedQuery` (instead of `dict[str, Any]`):
- `_parse_repo_source`
- `_parse_path`
- `parse_query`
- Updates the following functions in the `query_ingestion` module to take a query argument of type `ParsedQuery` (instead of `dict[str, Any]`):
- `run_ingest_query`
- `_ingest_directory`
- `_ingest_single_file`
- `_create_tree_structure`
- `_create_summary_string`
- `_extract_files_content`
- `_process_item`
- `_process_symlink`
- …

refactor: replace dict-based query with ParsedQuery dataclass

---

src/gitingest/cli.py

**Summary**
This PR fixes the`coroutine 'main' was never awaited` `RuntimeWarning` by introducing a synchronous Click command (`main`) that wraps an async function (`_async_main`) with `asyncio.run()`. This approach ensures that Click’s command decorators see a normal sync function, while the actual logic runs asynchronously (and is properly awaited).
**Key Changes**
- Added `_async_main(...)` function for the actual async logic.
- Updated the Click-decorated `main(...)` to be synchronous, which calls `_async_main(...)` via `asyncio.run()`.
- Removed the previous direct `async def` usage under Click’s command decorator.
**Benefits**
- No more `RuntimeWarning` about un-awaited coroutines.
- Cleaner separation of concerns between sync CLI handling and async operations.
May be related to …

refactor: refactor CLI to properly await async logic via a synchronous Click command

---

src/config.py
src/gitingest/cli.py
tests/test_cli.py

Summary:
1. Added test cases for CLI with default options.
2. Added test cases for CLI with custom options passed from the command line.
Implementation Notes:
1. Ensured the default CLI options create the expected output without additional arguments.
2. Validated custom CLI options (e.g., custom file paths, max size, and exclude patterns) also work seamlessly.
Alternative Options Considered:
Instead of actually creating and removing the output file during the test, I considered mocking the os.open and related functions. However, I opted to test the entire process end-to-end to ensure seamless functionality.

Enhancements: CLI Test Cases

---

src/config.py
src/gitingest/query_parser.py
src/main.py
src/query_processor.py
src/routers/dynamic.py
src/routers/index.py
src/utils.py
tests/conftest.py
tests/query_parser/test_git_host_agnostic.py
tests/query_parser/test_query_parser.py
tests/test_notebook_utils.py
tests/test_query_ingestion.py
tests/test_repository_clone.py

This PR centralizes key improvements in the application’s structure and testing approach:
1. **Lifespan & Cleanup in `utils.py`**  
- Moved the repository cleanup task, `rate_limit_exception_handler`, and `lifespan`  from `main.py` into a new `utils.py` module.
2. **Unified Template Usage**  
- Removed repeated `Jinja2Templates` instantiations, replacing them with the shared `TEMPLATES` from `config.py`.
- Updated routers, the main app, and query processors to reference `TEMPLATES` directly for more consistent template loading.
3. **Test Enhancements**  
- Adopted a “Given/When/Then” style for test docstrings, clarifying each test’s scenario and outcome.
- Parametrized certain tests (e.g., branch vs. commit distinction) to reduce duplication in `query_parser`.
- Used `pytest.warns` to …

refactor: code cleanup, utils extraction, and test improvements

---

src/server/templates/components/git_form.jinja
src/server/templates/components/result.jinja
src/static/js/utils.js

Made a couple of changes to finish the feature:
* Added some javascript code in `result.jinja` to add or remove file names to the patter input.
* Placed an `onchange` handler on the pattern selector to change CSS classes depending on whether "exclude" or "include" is selected. The simplest way to do this was to toggle all the classes, since it handles already selected files as well without any extra logic.
@cyclotruc feel free to let me know what you think! You also mentioned wanting to add some kind of notice to users that the items were clickable - do you think adding some text above the file tree would be the best way to do that?

Resolves #109, File Tree Lines can be Added to Exclude/Include Pattern Through Click

---

.github/workflows/ci.yml
setup.py
src/gitingest/config.py
src/gitingest/query_ingestion.py
src/gitingest/repository_clone.py
tests/test_repository_clone.py

Key changes:
- Added `_normalize_path` function to handle platform-specific path normalization
- Added `_normalize_path_str` function to ensure consistent forward slash separators in output
- Added `_get_encoding_list` function for cross-platform file encoding detection
- Enhanced Windows `symlink` handling in `_is_safe_symlink`
- Updated file content string generation to use normalized paths
- Improved file reading with multiple encoding attempts for better cross-platform compatibility
- Fixed path separator inconsistencies in test outputs
** Additionally, this project would not run on Windows Systems due to `setup.py` handling Readme File. 
Fixed the above as well

Improvement: Make the CLI work on windows

---

src/server/server_config.py

This replaces the "Tldraw" button to "Excalidraw" in the example repos of the front page.
I believe that showcasing Excalidraw in favor of Tldraw empowers open-source and permissive licensing.

feat: replace tldraw by excalidraw in EXAMPLE_REPOS

---

src/gitingest/query_ingestion.py

Added latin as an encoding, it fails to work with french characters without this. We don't all write good english. I had this issue because I got the error message below.
`
gitingest .
Error: 'charmap' codec can't encode characters in position 22-24: character maps to <undefined>
Aborted!
`
Now it works great.

Added latin as an encoding

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
pyproject.toml
setup.py
src/gitingest/cli.py
src/gitingest/ignore_patterns.py
src/gitingest/notebook_utils.py
src/gitingest/query_ingestion.py
src/gitingest/query_parser.py
src/gitingest/repository_clone.py
src/gitingest/repository_ingest.py
src/gitingest/utils.py
src/server/main.py
src/server/server_config.py
src/server/server_utils.py
tests/conftest.py
tests/query_parser/test_git_host_agnostic.py
tests/query_parser/test_query_parser.py
tests/test_cli.py

**Summary**
- **Commit 1**: Added Python 3.9 support by:
- Falling back to `ParamSpec` from `typing_extensions` instead of the standard `typing` module.
- Refactoring `match` statements introduced in Python 3.10, reverting them to if/elif blocks for compatibility.
- **Commit 2**: Extended support further down to Python 3.7 by:
- Eliminating usage of the walrus operator (`:=`).
- Replacing inline generics (e.g., `list[str]`, `dict[str, Any]`) with the older `List[str]`, `Dict[str, Any]` style.
- Updating the required Python version in `pyproject.toml` and `setup.py` to `>=3.7`.
- Relaxing certain pre-commit checks so that PyUpgrade and others won’t break 3.7 compatibility again.
**Details**
1. **CI Updates**: The GitHub Actions matrix now runs tests on Python 3.7, 3.8, 3.9, and all the way …

feat: Add Python 3.7 Support and Restore Compatibility with Older Syntax

---

src/gitingest/query_ingestion.py
src/gitingest/repository_ingest.py

- Removes the redundant `_normalize_path(path.resolve())` calls in `query_ingestion.py`, 
which were causing ingestion to fail on MacOS.
- **Resolves**:
- https://github.com/cyclotruc/gitingest/issues/179
- https://github.com/cyclotruc/gitingest/issues/182)
- Removes `ignore_errors=True` from `shutil.rmtree` to enable error handling during temporary directory cleanup.

fix: Fix MacOS path resolution failures and surface temp directory cleanup errors

---

src/gitingest/query_parser.py
src/gitingest/repository_ingest.py

- Added `gist.github.com` support (per [#175](https://github.com/cyclotruc/gitingest/issues/175))  
- Fixed `ingest_async` bug

feat: add gist.github.com support and fix ingest_async bug

---

src/gitingest/utils.py

This PR updates the `async_timeout` function signature to address a Pylance warning about `TypeVar` usage. Specifically, the function definition has been changed from:
```diff
-def async_timeout(seconds: int = 10) -> Callable[..., Callable[..., Awaitable[T]]]:
+def async_timeout(seconds: int = 10) -> Callable[[Callable[..., Awaitable[T]]], Callable[..., Awaitable[T]]]:

fix: Refine async_timeout to properly handle TypeVar usage

---

.pre-commit-config.yaml
requirements.txt
src/gitingest/query_ingestion.py

This pull request includes changes to the `src/gitingest/query_ingestion.py` file to enhance the query ingestion process by applying ignore patterns from a `.gitingest` file. The most important changes include importing the `tomllib` library and adding a new function to handle the `.gitingest` file.
Enhancements to query ingestion:
* [`src/gitingest/query_ingestion.py`](diffhunk://#diff-1b2905ac9d245e3923885fa9fd5aa435537ed4c9998e22ac2d0777006628633cR6): Imported the `tomllib` library to read TOML files.
* [`src/gitingest/query_ingestion.py`](diffhunk://#diff-1b2905ac9d245e3923885fa9fd5aa435537ed4c9998e22ac2d0777006628633cL901-R931): Added the `apply_gitingest_file` function to read the `.gitingest` file and update the query object with ignore patterns.
This feature introduces support for …

feat(cli):Add support for .gitingest file processing in query ingestion

---

README.md

The title attribute for the Microsoft Edge Add-ons link mistakenly referenced "Firefox Add-ons."  
Updated it to properly reflect "Microsoft Edge Add-ons" to avoid confusion.

fix: correct title attribute for Edge Add-ons link

---

src/gitingest/ingestion.py
src/gitingest/query_parsing.py
src/gitingest/utils/ingestion_utils.py

This PR introduces improvements to cross-platform path handling and directory inclusion:
1. **Windows Path Normalization**  
Backslashes are now converted to forward slashes in `_parse_patterns`, ensuring consistent pattern matching on Windows, macOS, and Linux.
2. **Directory Include Pattern Handling**  
If the path is a directory, a trailing slash is appended (e.g., `src/`), so that patterns like `src/*` properly match directories.
- **Fixes**: https://github.com/cyclotruc/gitingest/issues/205

fix: fix directory include pattern matching and normalize Windows paths

---

src/gitingest/cloning.py

As @filipchristiansen pointed out, the previous code was working by luck because it was not properly removing the filename but only the last character
I guess git checkout was handling the failing filename and falling back to parent directory
Now fixed with a Path object

fix subpath cloning

---

src/gitingest/cloning.py
src/gitingest/exceptions.py
src/gitingest/filesystem_schema.py
src/gitingest/ingestion.py
src/gitingest/output_formatters.py

This PR unifies the ingestion output flow for both directories and single files into a single function, `format_node`. It also removes several unused exceptions (`MaxFilesReachedError`, `MaxFileSizeReachedError`, and `AlreadyVisitedError`) and refines the partial clone subpath logic.
- **Reduced Duplication in `output_formatters.py`**  
Consolidated `format_directory` and `format_single_file` into a single `format_node` function, eliminating parallel code paths and clarifying how content is assembled and displayed.
- **Removed an Unused Exception**  
Deleted `MaxFilesReachedError`, `MaxFileSizeReachedError`, and `AlreadyVisitedError` from `exceptions.py` since they were no longer being used.
- **Simplified Cloning Logic**  
Streamlined partial clone handling and removed extraneous steps …

refactor: refactor ingestion output, remove unused exception and simplify cloning & FileSystem logic

---

tests/conftest.py

The `IngestionQuery` class no longer accepts a parameter named `pattern_type`. This change removes the outdated parameter from the `sample_query` fixture, ensuring consistency with the updated `IngestionQuery` signature and preventing any confusion in tests.

Remove leftover pattern_type usage in IngestionQuery fixture

---

.pre-commit-config.yaml
pyproject.toml
requirements.txt
src/gitingest/ingestion_schema.py

This PR removes dependencies that are no longer needed (`chardet`, `fastapi-analytics`) and updates various Python packages to versions that address known security vulnerabilities. Specifically, `fastapi`, `starlette`, and `uvicorn` have been pinned to ensure patches for identified issues are applied. The changes also include a small tweak to the ingestion schema to align with the latest `pydantic` configuration pattern.
**What Changed?**
- Removed references to `chardet` and `fastapi-analytics` in `.pre-commit-config.yaml` and `requirements.txt`.
- Pinned `fastapi[standard]`, `starlette`, and `uvicorn` to versions fixing their respective security issues.
- Added `pydantic` explicitly to `requirements.txt` and `pyproject.toml`.
- Updated `IngestionQuery` model to use the new …

chore: remove unused dependencies and pin fastapi/starlette/uvicorn to fix vulnerabilities

---

.pre-commit-config.yaml
src/gitingest/__init__.py
src/gitingest/cli.py
src/gitingest/cloning.py
src/gitingest/config.py
src/gitingest/entrypoint.py
src/gitingest/exceptions.py
src/gitingest/filesystem_schema.py
src/gitingest/ingestion.py
src/gitingest/ingestion_schema.py
src/gitingest/query_parsing.py
src/gitingest/utils/ignore_patterns.py
src/gitingest/utils/ingestion_utils.py
src/gitingest/utils/notebook_utils.py
src/gitingest/utils/path_utils.py
src/gitingest/utils/query_parser_utils.py
src/gitingest/utils/textfile_checker_utils.py
src/gitingest/utils/timeout_wrapper.py
src/server/main.py
src/server/query_processor.py
src/server/routers/__init__.py
src/server/routers/download.py
src/server/routers/dynamic.py
src/server/routers/index.py
src/server/server_config.py
src/server/server_utils.py
tests/test_cli.py
tests/test_flow_integration.py

This PR updates the pre-commit configuration by running `pre-commit autoupdate`.

chore: run pre-commit autoupdate

---

.vscode/launch.json
src/gitingest/ingestion.py
src/gitingest/output_formatters.py
src/gitingest/schemas/filesystem_schema.py

Some changes to how we handle symlinks. We no longer resolve them, which should reduce the complexity by a nice bit.
We also now show the target name in the output.
I also added a `launch.json` file for debugging because it took me a while to figure out how to get the debugger to work.
Yeah, that's it.
Please test before merging because I'm a bit of a dingus sometimes

refactor: rework how symlinks are processed (no longer resolve)

---

src/gitingest/schemas/filesystem_schema.py
src/gitingest/utils/file_utils.py

This PR prevents crash due to #230 #231 
This is a 🤷-style PR because idk if adding more duct tape safeguards to the encoding process is the way to go but I'm opening this so we can discuss at least.

"fix": Error: UTF-16 stream does not start with BOM

---

src/gitingest/cli.py
src/gitingest/ingestion.py
src/gitingest/utils/ingestion_utils.py
tests/test_ingestion.py

Allows pattern matching to check against files within directories. Changes the logic of `_should_include` to traverse all directories such that pattern matching can happen to files within them. Also adds some logic to `_process_node` to not include folders which have no children; i.e. when no files within them had passed the include/ignore filter.
Also adds a few unit tests of some include/ignore patterns against the sample `temp_directory`.
imo a more extensible solution would be to use glob, but that seemed like it'd require a more significant restructuring.
closes #224

fix: traverse directories to allow pattern matching of files within them

---

README.md
src/gitingest/cli.py
src/gitingest/cloning.py
src/gitingest/config.py
src/gitingest/entrypoint.py
src/gitingest/query_parsing.py
src/gitingest/schemas/ingestion_schema.py
src/gitingest/utils/git_utils.py
src/gitingest/utils/os_utils.py
tests/test_repository_clone.py

This PR enables **Gitingest** to ingest **private GitHub repositories** and resolves the long-standing sparse-checkout CLI mismatch.
| Area               | What’s new                                                                                                                                                                                                       |
| ------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **CLI**            | `--token/-t` flag (with `GITHUB_TOKEN` env-var fallback) to supply a GitHub PAT. …

feat: add private-repo support to CLI & core (UI coming next)

---

.pre-commit-config.yaml
README.md
src/gitingest/cli.py
src/gitingest/entrypoint.py
tests/test_cli.py

This change introduces the ability for users to direct the output of the gitingest tool to standard output (stdout) instead of writing to a file. This is useful for piping the output to other commands or viewing it directly in the terminal.
**Fixes** https://github.com/cyclotruc/gitingest/issues/225

Add option to output digest to stdout

---

src/gitingest/entrypoint.py
src/gitingest/query_parsing.py
src/server/query_processor.py
src/server/routers/dynamic.py
src/server/routers/index.py
src/server/templates/components/git_form.jinja
tests/test_flow_integration.py
tests/test_repository_clone.py

Until now the [gitingest.com](gitingest.com) web UI could ingest only **public** repositories.  
Teams often need to analyse private GitHub repos, so we’re adding a way to supply a personal access token (PAT).
| Area | Key changes |
|------|-------------|
| **UI** | • New “🔒 Private Repository” checkbox in `git_form.jinja` that reveals a masked PAT field.<br>• Checkbox state + token are posted with the form. |
| **Server routes** | • `index.py`, `dynamic.py`, `query_processor.py` accept `token` from the form and thread it downstream. |
| **Ingestion stack** | • `gitingest.entrypoint.parse_query` and `query_parsing` now carry `token`, letting `try_domains_for_user_and_repo()` resolve bare `user/repo` slugs against GitHub also when a PAT is present. |
| **Tests** | • Added `"token": ""` to …

feat(web-ui): add private-GitHub ingestion via PAT

---

README.md

Document how to access specific subdirectories using GitHub tree URLs with gitingest repo examples.

Add subdirectory URL syntax documentation to README

---

src/server/templates/components/git_form.jinja
src/static/js/utils.js

**What it does**
* Updates the file-size slider label in `git_form.jinja` and the `formatSize` helper in `utils.js` to show **kB / MB** instead of the misleading **kb / mb**.
* No behaviour or API changes.
**Why**
* Lower-case “b” denotes *bits*. Our UI currently claims kilobits/megabits while the backend logic actually works in *bytes*. This patch fixes that mismatch.
**Discussion**
* We’re standardising on correct decimal prefixes for now. I’m still weighing a full switch to IEC binary prefixes (KiB/MiB) and have asked @cyclotruc for input.
**Thanks**
* Shout-out to @Self-Perfection for catching the issue in https://github.com/cyclotruc/gitingest/pull/293

fix(ui): use proper decimal prefixes (kB / MB) in file-size selector

---

src/server/templates/components/result.jinja

When the user clicks a file or directory in the directory structure tree, the full relative path should be copied into the pattern input field. Currently, clicking on nested files in the tree inserts an incorrect or incomplete path. This pull request addresses that issue.
Closes #288
The `getFileName` and `toggleFile` functions in `src/server/templates/components/result.jinja` were modified to correctly compute the full path of a clicked file by traversing DOM elements and extracting its parent directories.
Previously, the regex used to detect the start of the filename was `/[a-zA-Z0-9]/`. It has now been updated to `/[a-zA-Z0-9_.-]/` to correctly handle filenames starting with a dot or underscore (e.g., `.gitignore`, `__init__.py`). An alternative approach could be to match the first …

fix(ui): update directory-picker logic to compute full file paths

---

src/server/templates/components/git_form.jinja

The PAT help link was positioned absolutely, which could overlap the example-repository buttons. We now increase the vertical margin from `mb-8` to `mb-12` to the controls row whenever the `Private Repository` checkbox is checked (`toggleAccessSettings`), ensuring enough vertical space while retaining the existing absolute positioning.
Fixes Issue https://github.com/cyclotruc/gitingest/issues/301

fix: fix spacing of PAT token section in Git-Form to avoid UI overlap

---

src/server/main.py
src/server/templates/components/badge_new.jinja
src/server/templates/components/git_form.jinja
src/server/templates/components/navbar.jinja
src/static/llm.txt

This PR adds a llm.txt route returning a raw-text version of a .md documentation that will help LLMs explain or use gitingest
Also some "new" labels on the most recent features that will go away someday

feat: add /llm.txt

---

src/gitingest/utils/query_parser_utils.py
tests/query_parser/test_git_host_agnostic.py
tests/query_parser/test_query_parser.py

Users working with self-hosted Git services (e.g. university or company GitLab) were blocked by `Unknown domain '<host>' in URL`.
1. **Heuristic host detection**
* `_looks_like_git_host` now treats any host that starts with `git.` or `gitlab.` as a valid Git host.
* `_validate_host` delegates to this heuristic when the domain is not in `KNOWN_GIT_HOSTS`.
2. **Doc-string updates** describing the new rules.
3. **Test updates**
* Added real-world examples `git.rwth-aachen.de/medialab/19squared` and `gitlab.alpinelinux.org/alpine/apk-tools`.
* Refactored `test_parse_query_without_host` to expect a `ValueError` when a host outside `KNOWN_GIT_HOSTS` is supplied without an explicit domain (slug variant: `user/repo`).
* Users can now ingest from URLs on the form `git.example.com/user/repo`.
* …

feat(parser): relax host validation to support self-hosted GitLab instances and update tests

---

src/server/templates/components/git_form.jinja

In the PAT section, the `Get your token` link overlaps the sample-repo buttons. The `New` badge and the PAT input also overflow due to the use of `position: absolute`. This pull request updates the styles in that section by removing absolute positioning while preserving a similar layout.
Closes #328
- Replaced `flex` layout with CSS `grid` for more flexibility
- Added custom styles to the PAT checkbox to better align with the overall design
The grid layout is applied to the `#controlsRow` element, which contains three child components: Pattern type selector, max file size slider, and PAT section.
- Default:
- Single column layout (`grid-cols-1`)
- `gap-6` between items
- `sm` screens:
- Two columns with a `3:2` width ratio (`grid-cols-[3fr_2fr]`)
- Horizontal gap increased (`gap-x-10`)
- …

fix(ui): update layout in PAT section to avoid overlaps & overflows

---

src/server/templates/components/git_form.jinja

- Adds a small gray **ⓘ** icon inside the **Personal Access Token** input.
- Tooltip (hover / focus) shows four concise bullets:  
* PAT is never stored in the backend
* Used once for cloning, then discarded from memory
* No browser caching
* Cloned repos are deleted after processing
A lightweight inline tooltip keeps the form compact while still answering the “where does my token go?” question.
Closes #321

feat(ui): add inline tooltip for Personal Access Token privacy info

---

.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
src/gitingest/cli.py
src/gitingest/clone.py
src/gitingest/query_parser.py
src/gitingest/utils/auth.py
src/gitingest/utils/compat_typing.py
src/gitingest/utils/exceptions.py
src/gitingest/utils/git_utils.py
src/gitingest/utils/ignore_patterns.py
src/server/query_processor.py
src/server/routers/download.py
tests/test_clone.py
tests/test_git_utils.py

GitHub-PAT handling had drifted into multiple helper layers, making it hard to reason about where a token is verified and who is responsible for failure messages. This PR pushes all validation to the topmost entry points, simplifies remote-repo detection, and performs a round of general housekeeping discovered along the way.
| Category             | Details                                                                                                                                                                                                                                                                                     |
| -------------------- | ----------------------------------------------------------------------------------------------------------------------------------------- …

refactor: centralize PAT validation, streamline repo checks & misc cleanup

---

.dockerignore
.gitignore

Cleanup `.gitignore` and `.dockerignore`

cleanup `.gitignore`

---

.github/ISSUE_TEMPLATE/bug_report.yml

Adds a YAML-based **GitHub Issue Form** (`.github/ISSUE_TEMPLATE/bug_report.yml`) for **bug reports**.
* Collects key details up front – interface (Web UI / CLI / PyPI), repo URL, host, revision, OS, versions, steps to reproduce, etc.
* Addresses part of https://github.com/coderamp-labs/gitingest/issues/359
* No other code or docs touched.

docs: add GitHub Issue Form for bug reports

---

.docker/minio/setup.sh
.env.example
.pre-commit-config.yaml
README.md
compose.yml
pyproject.toml
requirements.txt
src/gitingest/query_parser.py
src/gitingest/schemas/ingestion.py
src/server/models.py
src/server/query_processor.py
src/server/routers/ingest.py
src/server/s3_utils.py
src/static/js/utils.js
tests/conftest.py
tests/query_parser/test_git_host_agnostic.py
tests/server/test_flow_integration.py

Closes https://github.com/coderamp-labs/issue-board/issues/13

feat: implement S3 integration for storing and retrieving digest files

---

.github/workflows/rebase-needed.yml

Why?
PRs are usually open for a few days until a maintainer can take a look. When this happens a Pull Request (PR) might already be outdated without the author being notified of this. A maintainer either has to resolve them (which takes time) or has to ping the author. This creates a feedback loop that can be reduced by this action.
This actions achieve this with minimal noise (no comment bloat) by adding a label to a PR if it has merge conflicts. This means the author has a single overview of which PRs need a rebase by using their list of created PRs. At the same time the maintainer has a simple filter for PRs that have merge conflicts.
See [eps1lon/actions-label-merge-conflict](https://github.com/eps1lon/actions-label-merge-conflict?tab=readme-ov-file#why)

ci: add workflow to label PRs needing rebase

---

src/server/main.py
src/server/query_processor.py
src/server/server_config.py
src/server/server_utils.py

This PR refactors the repository cleanup mechanism from a background cleanup task to immediate cleanup after each processing operation, improving resource management and simplifying the codebase.
- **Before**: Background task periodically scanned and deleted repositories older than 1 hour
- **After**: Immediate cleanup after each repository processing (success or failure)
- Removed `lifespan` import and usage from FastAPI app initialization
- Simplified app setup by removing the lifespan context manager
- Added new `_cleanup_repository()` function for immediate cleanup
- Integrated cleanup calls in `process_query()`:
- Cleanup on processing failure (in exception handler)
- Cleanup on successful processing completion
- Uses `shutil.rmtree()` with proper error handling and logging
- Removed …

fix: improved server side cleanup after ingest

---

compose.yml
src/server/query_processor.py
src/server/s3_utils.py

fix: make cache aware of subpaths

---

.github/workflows/docker-build.ecr.yml
.github/workflows/docker-build.ghcr.yml
Dockerfile
src/server/main.py
src/server/routers/dynamic.py
src/server/routers/index.py
src/server/server_config.py
src/server/templates/components/footer.jinja
src/server/templates/components/navbar.jinja

feat(web): add version info display
